availability_rules
    ::= 'member' ( 'did' ('not'? ( 'action' '{action code}' | 'check-in'  '{check-in code}') (( 'with' '{attribute name}' ( '>=' | '<=' | '=' | '>' | '<' ) '{attribute value}' ) ( '&' '{attribute name}' ( '>=' | '<=' | '=' | '>' | '<') '{attribute value}' )*)? |'something'|'nothing') ) OCCURRENCE_FILTER? PERIOD_FILTER? MOMENT_FILTER?
    | 'member' 'has' 'not'? 'completed' '{challenge code}'  OCCURRENCE_FILTER? PERIOD_FILTER? MOMENT_FILTER?
    | 'member' 'has' 'not'? (('gained' | 'lost') 'NUMBER'?  ('points' '{level code}' | 'prize' '{prize code}'|'tag' '{tag code}') ) OCCURRENCE_FILTER? PERIOD_FILTER?
    | SYSTEM_CONDITION
    | 'tag' '{tag code}' ( '>=' | '<=' | '=' | '>' | '<' ) 'NUMBER'?
    | 'level' '{level code}' ( '>=' | '<=' | '=' | '>' | '<' ) 'NUMBER'?
    | 'in zone' ('{zone code}' (',' '{zone code}')*)
    | 'challenge' '{challenge code}'
    | 'belongs to smartlist' ('{smartlist code}' (',' '{smartlist code}')*)