challenge_reward_rules
         ::= ('action'  '{action code}' (  'NUMBER' 'times' ( 'within' 'NUMBER' ('minutes, hours, days, weeks, months, years') )? )* ( 'with tag' '{tag code}' | 'with data'  '{attribute name}'  ( '>=, <=, =, >, <' )  '{attrbitute value}' | 'in zone'  '{zone code}' (  ','  '{zone code}' )* | 'near'  'NUMBER'  'of beacon'  '{beacon code}' (  ','  '{beacon code}' )* )*
           | 'challenge'  '{challenge code}' (  'NUMBER' 'times' ( 'within' 'NUMBER' ('minutes, hours, days, weeks, months, years') )? )* ( 'in zone'  '{zone code}' (  ','  '{zone code}' )* | 'near'  'NUMBER'  'of beacon'  '{beacon code}' (  ','  '{beacon code}' )* )*
           | 'member'  ( 'level' | 'point' )  '{level code}'  ('>=, <=, =, >, <')  'NUMBER'
           | 'member'  'tag'  '{tag code}'  ( '>=, <=, =, >, <' )  'NUMBER'
           | 'member'  'in zone'  '{zone code}' (  ','  '{zone code}' )* (  'for'  'NUMBER'  ('minutes, hours, days, weeks, months, years') )?)+ ( 'give'  'NUMBER'  '{reward code}')+
           | 'member' ( 'did' ('not'? ( 'action' '{action code}' | 'check-in'  '{check-in code}') (( 'with' '{attribute name}' ( '>=' | '<=' | '=' | '>' | '<' ) '{attribute value}' ) ( '&' '{attribute name}' ( '>=' | '<=' | '=' | '>' | '<') '{attribute value}' )*)? |'something'|'nothing') ) OCCURRENCE_FILTER? PERIOD_FILTER?
           | 'member' 'has' 'not'? ('completed' '{challenge code}' | ('gained' | 'lost') 'NUMBER'?  ('points' '{level code}' | 'prize' '{prize code}'|'tag' '{tag code}') ) OCCURRENCE_FILTER? PERIOD_FILTER?
