Moment_Filter
::= (
'before' ('hh:mm' ('am'|'pm')?)
|'after' ('hh:mm'  ('am'|'pm')?)
|'between' ('hh:mm'  ('am'|'pm')?) 'and' ('hh:mm' ('am'|'pm')?)
|'during the' ('night'|'morning'|'afternoon'|'evening')
)
