PERIODE_LITE
::= ((('before' | 'after') 'YYYY-MM-DD' ('hh:mm'  ('am'|'pm')?)?) | ('between' 'YYYY-MM-DD' ('hh:mm'  ('am'|'pm')?)? 'and' 'YYYY-MM-DD' ('hh:mm'('am'|'pm')?)?)
| ('in last' (('minute' | 'hour' | 'day' | 'week' | 'month' | 'year')|'NUMBER' ('minutes' | 'hours' | 'days' | 'weeks' | 'months' | 'years'))) )